//! P0640d — OpenSCAD recipe exporter: OTD → .scad source (parametric, editable).

use crate::world::eval::World;
use std::fmt::Write as _;

/// Translate the OTD world into an OpenSCAD script using transformed
/// polyhedra (the mesh truth, not primitive approximations).
pub fn to_scad(world: &World, title: &str) -> String {
    let mut s = String::new();
    let _ = writeln!(s, "// OTD → OpenSCAD export — {}", title);
    let _ = writeln!(s, "// generated by OTD (pure Rust). Units: millimeters.");
    let _ = writeln!(s, "$fn = 48;");
    for (i, part) in world.parts.iter().enumerate() {
        if part.hidden {
            continue;
        }
        let color = part.color.map(|c| format!("[{:.4},{:.4},{:.4}]", c.r(), c.g(), c.b()))
            .unwrap_or_else(|| "[0.8,0.8,0.8]".into());
        let _ = writeln!(s, "// part: {} — mass {:.1} g", part.name, part.mass_g);
        let _ = writeln!(s, "color({}) polyhedron(", color);
        let _ = writeln!(s, "  points = [");
        for v in &part.mesh.verts {
            let _ = writeln!(s, "    [{:.6},{:.6},{:.6}],", v.x(), v.y(), v.z());
        }
        let _ = writeln!(s, "  ],");
        let _ = writeln!(s, "  faces = [");
        for t in &part.mesh.tris {
            let _ = writeln!(s, "    [{},{},{}],", t[0], t[1], t[2]);
        }
        let _ = writeln!(s, "  ]");
        let _ = writeln!(s, ");");
        let _ = i;
    }
    s
}
